//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoughtPacket
    {
        public int BoughtPacketId { get; set; }
        public int UserId { get; set; }
        public int InfoId { get; set; }
        public string ReceiptImg { get; set; }
        public System.DateTime BoughtTime { get; set; }
        public string BoughtIP { get; set; }
        public int PacketType { get; set; }
        public int Status { get; set; }
        public int Price { get; set; }
        public string Note { get; set; }
    
        public virtual PacketInformations PacketInformations { get; set; }
        public virtual Users Users { get; set; }
    }
}
