//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barcode_Restaurant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Packets
    {
        public int PacketId { get; set; }
        public int UserId { get; set; }
        public int PacketType { get; set; }
        public System.DateTime RemainingUsageTime { get; set; }
        public System.TimeSpan DayStartTime { get; set; }
        public System.TimeSpan DayEndTime { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
